@Library('mylibrary')_
node('built-in')
{
    stage('GD')
    {
        cicd.GD("maven")
    }
    stage('MB')
    {
        cicd.MB()
    }
    stage('CDeploy')
    {
        cicd.CDeploy("SPSL1","54.176.121.38","t4")
    }
    stage('CT')
    {
        cicd.CT("FunctionalTesting")
    }
    stage('CDeliervy')
    {
        cicd.CDelivery("SPSL1","54.176.121.38","p4")
    }
}

